### ISSUE TITLE
Upstream Changes - Resolving merges

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/flyingpigeon#25]
[flyingpigeon/utils.py](https://github.com/Ouranosinc/flyingpigeon/blob/bird-house-master-1.2.0/flyingpigeon/utils.py) seems to be a file that was largely replaced by `eggshell`. Git has removed the imports (as this code was likely the same in both at one point. My questions are:

- Should we be referring to the more recent Birdhouse/master version here?
- Has much of the code that is in our branch been replaced by eggshell? or should both versions be preserved as their functions aren't synonymous?

---
[flyingpigeon/processes](https://github.com/Ouranosinc/flyingpigeon/tree/bird-house-master-1.2.0/flyingpigeon/processes/) is conflicting due to the PEP8 changes I performed upstream a few months ago. I'll be taking the upstream versions here for 99% of the code. I'll still review to ensure that nothing substantial is lost/replaced.

---
[flyingpigeon/profiles](https://github.com/Ouranosinc/flyingpigeon/tree/bird-house-master-1.2.0/profiles) contains mostly server-specific code for our builds. Is there a way to prevent this from being pushed to Bird-house master when we try to push upstream?

**Comment by huard** [comment]
Yes, we want to use eggshell rather than flyingpigeon/utils

I don't think the PAVICS specific code uses eggshell yet. It's on the to do list. 

If the merge is too ugly, I think we can simply take the new functions developed in PAVICS and add them to birdhouse, instead of doing a full merge. 

Sounds good.

Good question. How is it done for the other birds with no local fork ?

**Comment by Zeitsperre** [comment]
Merging to upstream master was performed in 2018 with https://github.com/bird-house/flyingpigeon/pull/262. Closing and archiving this fork.
